# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AwesomeProject' do
 
pod 'React', path:'../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'RCTWebSocket', # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  

  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  # Third party deps podspec link
  pod 'DoubleConversion', podspec: '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec' 
  pod 'glog', podspec: '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', podspec: '../node_modules/react-native/third-party-podspecs/Folly.podspec' 	 	
  pod 'react-native-amap3d', path: '../node_modules/react-native-amap3d/lib/ios'
end


